AlibabaRazboinik/habit_tracker

- README.md
- src/main/java/com/example/habitstracker/controllers/UserController.java
- src/main/java/com/example/habitstracker/dto/UserDTO.java
- src/main/java/com/example/habitstracker/exceptions/UserExistException.java
- src/main/java/com/example/habitstracker/exceptions/UserNotFoundException.java
- src/main/java/com/example/habitstracker/mappers/UserMapper.java
- src/main/java/com/example/habitstracker/models/User.java
- src/main/java/com/example/habitstracker/repository/UserRepository.java
- src/main/java/com/example/habitstracker/security/JWTLoginFilter.java
- src/main/java/com/example/habitstracker/services/AppUserDetailsService.java
- src/main/java/com/example/habitstracker/services/UserService.java
- src/main/resources/HabitTracker.postman_collection.json
- src/test/java/com/example/habitstracker/HabitstrackerApplicationTests.java
- src/test/java/com/example/habitstracker/services/UserServiceTest.java
Use username instead of nickname
> User "username" everywhere

- src/main/java/com/example/habitstracker/controllers/UserController.java
https://github.com/AlibabaRazboinik/habit_tracker/issues/18
> Убрал метод add_user из api

- src/main/java/com/example/habitstracker/controllers/HabitController.java
- src/main/java/com/example/habitstracker/controllers/HabitListController.java
- src/main/java/com/example/habitstracker/controllers/UserController.java
- src/main/resources/HabitTracker.postman_collection.json
https://github.com/AlibabaRazboinik/habit_tracker/issues/17
> Use @RequestMapping

- src/main/java/com/example/habitstracker/Constants.java
- src/main/java/com/example/habitstracker/configuration/AuthenticationManagerConfig.java
- src/main/java/com/example/habitstracker/configuration/ObjectMapperConfig.java
- src/main/java/com/example/habitstracker/configuration/PasswordEncoderConfig.java
- src/main/java/com/example/habitstracker/configuration/SecurityConfig.java
- src/main/java/com/example/habitstracker/models/listeners/UserListener.java
- src/main/java/com/example/habitstracker/security/JWTAuthenticationFilter.java
- src/main/java/com/example/habitstracker/security/JWTLoginFilter.java
- src/main/java/com/example/habitstracker/security/TokenAuthenticationService.java
- src/main/java/com/example/habitstracker/security/UserCredentials.java
- src/test/java/com/example/habitstracker/api/AuthTest.java
- src/test/java/com/example/habitstracker/dsl/AuthDSL.java
https://github.com/AlibabaRazboinik/habit_tracker/issues/24
> Надо сохранять id пользователя в jwt

- src/main/java/com/example/habitstracker/advices/UserAdvice.java
- src/main/java/com/example/habitstracker/controllers/HabitController.java
- src/main/java/com/example/habitstracker/controllers/HabitListController.java
- src/main/java/com/example/habitstracker/dto/HabitDTO.java
- src/main/java/com/example/habitstracker/dto/IdDTO.java
- src/main/java/com/example/habitstracker/exceptions/ErrorCodes.java
- src/main/java/com/example/habitstracker/exceptions/HabitNotFoundException.java
- src/main/java/com/example/habitstracker/exceptions/UserNotFoundException.java
- src/main/java/com/example/habitstracker/mappers/HabitMapper.java
- src/main/java/com/example/habitstracker/models/Habit.java
- src/main/java/com/example/habitstracker/repository/HabitRepository.java
- src/main/java/com/example/habitstracker/services/HabitService.java
- src/main/java/com/example/habitstracker/services/UserService.java
- src/test/java/com/example/habitstracker/HabitstrackerApplicationTests.java
- src/test/java/com/example/habitstracker/TestUserBuilder.java
- src/test/java/com/example/habitstracker/api/AuthTest.java
- src/test/java/com/example/habitstracker/api/HabitTest.java
- src/test/java/com/example/habitstracker/dsl/AuthDSL.java
- src/test/java/com/example/habitstracker/dsl/HabitDSL.java
- src/test/java/com/example/habitstracker/services/HabitServiceTest.java
- src/test/java/com/example/habitstracker/utils/DatabaseUtils.java
- src/test/resources/HabitTracker.postman_collection.json
https://github.com/AlibabaRazboinik/habit_tracker/issues/4
> habit delete, get, put

- src/main/java/com/example/habitstracker/controllers/HabitListController.java
- src/main/java/com/example/habitstracker/dto/HabitListDTO.java
- src/main/java/com/example/habitstracker/mappers/HabitListMapper.java
2. https://github.com/AlibabaRazboinik/habit_tracker/issues/29
> 1. убрали костыль от циклической

- src/test/java/com/example/habitstracker/HabitstrackerApplicationTests.java
- src/test/java/com/example/habitstracker/api/AuthTest.java
- src/test/java/com/example/habitstracker/api/HabitTest.java
- src/test/java/com/example/habitstracker/dsl/HabitDSL.java
- src/test/java/com/example/habitstracker/services/HabitListServiceTest.java
- src/test/java/com/example/habitstracker/services/HabitServiceTest.java
- src/test/java/com/example/habitstracker/services/UserServiceTest.java
- src/test/java/com/example/habitstracker/utils/DatabaseUtils.java
https://github.com/AlibabaRazboinik/habit_tracker/issues/32
> Написать базовые тесты на сервисы

- src/main/java/com/example/habitstracker/configuration/AuthenticationManagerConfig.java
- src/main/java/com/example/habitstracker/configuration/SecurityConfig.java
- src/main/java/com/example/habitstracker/configuration/WebSecurityCustomizerConfig.java
- src/main/java/com/example/habitstracker/security/JWTLoginFilter.java
https://github.com/AlibabaRazboinik/habit_tracker/issues/40
> Rewrite SecurityConfig. Don't use deprecated class

- src/main/java/com/example/habitstracker/controllers/HabitApiImpl.java
- src/main/resources/api.yaml
https://github.com/AlibabaRazboinik/habit_tracker/issues/59
> При создании привычки возвращать ее id

- src/main/java/com/example/habitstracker/mappers/UserMapper.java
https://github.com/AlibabaRazboinik/habit_tracker/issues/66
> Дописать UserMapper

- src/main/java/com/example/habitstracker/controllers/HabitListApiImpl.java
- src/main/java/com/example/habitstracker/mappers/UserMapper.java
- src/main/java/com/example/habitstracker/models/UserEntity.java
- src/main/java/com/example/habitstracker/models/listeners/UserListener.java
- src/main/java/com/example/habitstracker/repository/UserRepository.java
- src/main/java/com/example/habitstracker/services/AppUserDetailsService.java
- src/main/java/com/example/habitstracker/services/HabitListService.java
- src/main/java/com/example/habitstracker/services/HabitService.java
- src/main/java/com/example/habitstracker/services/UserService.java
- src/test/java/com/example/habitstracker/TestUserBuilder.java
- src/test/java/com/example/habitstracker/api/AuthTest.java
- src/test/java/com/example/habitstracker/api/HabitTest.java
- src/test/java/com/example/habitstracker/dsl/AuthDSL.java
- src/test/java/com/example/habitstracker/dsl/UserDSL.java
- src/test/java/com/example/habitstracker/services/HabitListServiceTest.java
- src/test/java/com/example/habitstracker/services/HabitServiceTest.java
- src/test/java/com/example/habitstracker/services/UserServiceTest.java
- src/test/java/com/example/habitstracker/utils/DatabaseUtils.java
https://github.com/AlibabaRazboinik/habit_tracker/issues/48
> Используй сервисы вместо репозиториев

- src/main/java/com/example/habitstracker/controllers/AuthApiImpl.java
- src/main/java/com/example/habitstracker/controllers/HabitApiImpl.java
- src/main/java/com/example/habitstracker/controllers/HabitListApiImpl.java
- src/main/java/com/example/habitstracker/controllers/UserApiImpl.java
- src/main/java/com/example/habitstracker/exceptions/ErrorCodes.java
- src/main/java/com/example/habitstracker/exceptions/MapperNotFound.java
- src/main/java/com/example/habitstracker/exceptions/RepresentableExceptionMapper.java
- src/main/java/com/example/habitstracker/filters/ExceptionHandlerFilter.java
- src/main/java/com/example/habitstracker/mappers/HabitListMapper.java
- src/main/java/com/example/habitstracker/mappers/HabitMapper.java
- src/main/java/com/example/habitstracker/mappers/Mapper.java
- src/main/java/com/example/habitstracker/mappers/UserMapper.java
- src/main/java/com/example/habitstracker/services/HabitListService.java
- src/main/java/com/example/habitstracker/services/MapperService.java
- src/main/java/com/example/habitstracker/services/UserService.java
- src/test/java/com/example/habitstracker/integration/tests/AuthTest.java
- src/test/java/com/example/habitstracker/integration/tests/HabitTest.java
- src/test/java/com/example/habitstracker/integration/utils/dsl/AuthDSL.java
- src/test/java/com/example/habitstracker/integration/utils/dsl/HabitDSL.java
- src/test/java/com/example/habitstracker/unit/tests/AbstractUnitTest.java
- src/test/java/com/example/habitstracker/unit/tests/HabitListServiceTest.java
- src/test/java/com/example/habitstracker/unit/tests/HabitstrackerApplicationTests.java
- src/test/java/com/example/habitstracker/unit/tests/UserServiceTest.java
https://github.com/AlibabaRazboinik/habit_tracker/issues/73
> Add MappingService

- .gitignore
- src/main/resources/logback.xml
https://github.com/AlibabaRazboinik/habit_tracker/issues/97
> Сконфигурировать логгер

- pom.xml
https://github.com/AlibabaRazboinik/habit_tracker/issues/38
> Remove Jackarta

- src/main/resources/api.yaml
https://github.com/AlibabaRazboinik/habit_tracker/issues/70
> Написать документацию в api.yaml

- src/main/java/com/example/habitstracker/configuration/SwaggerConfig.java
- src/main/java/com/example/habitstracker/configuration/WebSecurityCustomizerConfig.java
- src/main/java/com/example/habitstracker/constants/ExceptionTextConstants.java
- src/main/java/com/example/habitstracker/constants/OpenApiConstants.java
- src/main/java/com/example/habitstracker/constants/TableNameConstants.java
- src/main/java/com/example/habitstracker/constants/ValidationConstants.java
- src/main/java/com/example/habitstracker/exceptions/HabitListNotFoundException.java
- src/main/java/com/example/habitstracker/exceptions/HabitNotFoundException.java
- src/main/java/com/example/habitstracker/exceptions/MapperNotFound.java
- src/main/java/com/example/habitstracker/exceptions/UserExistException.java
- src/main/java/com/example/habitstracker/exceptions/UserNotFoundException.java
- src/main/java/com/example/habitstracker/exceptions/auth/EmptyAuthorizationHeaderException.java
- src/main/java/com/example/habitstracker/exceptions/auth/IncorrectClaimsException.java
- src/main/java/com/example/habitstracker/exceptions/auth/IncorrectCredentialsException.java
- src/main/java/com/example/habitstracker/exceptions/auth/IncorrectJWTException.java
- src/main/java/com/example/habitstracker/exceptions/auth/SkippedAuthorizationHeaderException.java
- src/main/java/com/example/habitstracker/models/Habit.java
- src/main/java/com/example/habitstracker/models/HabitList.java
- src/main/java/com/example/habitstracker/models/UserEntity.java
- src/main/java/com/example/habitstracker/validation/annotations/AtLeastOneDigit.java
- src/main/java/com/example/habitstracker/validation/annotations/AtLeastOneLetter.java
- src/main/java/com/example/habitstracker/validation/annotations/OnlyLettersDigitsUnderscore.java
https://github.com/AlibabaRazboinik/habit_tracker/issues/56
> Вынести все в константы

- src/main/java/com/example/habitstracker/controllers/AuthApiImpl.java
- src/main/java/com/example/habitstracker/controllers/HabitApiImpl.java
- src/main/java/com/example/habitstracker/controllers/HabitListApiImpl.java
- src/main/java/com/example/habitstracker/controllers/UserApiImpl.java
- src/main/resources/logback.xml
- src/main/resources/templates/pojo.mustache
https://github.com/AlibabaRazboinik/habit_tracker/issues/99
> Сделать логгирование всех запросов

- src/test/java/com/example/habitstracker/integration/utils/CleanerService.java
https://github.com/AlibabaRazboinik/habit_tracker/issues/74
> Заменить Lambda на Runnable

- src/main/java/com/example/habitstracker/constants/ApiConstants.java
- src/main/java/com/example/habitstracker/controllers/UserApiImpl.java
- src/main/java/com/example/habitstracker/mappers/UserMapper.java
- src/main/java/com/example/habitstracker/models/UserPassword.java
- src/main/java/com/example/habitstracker/models/listeners/PasswordListener.java
- src/main/java/com/example/habitstracker/models/listeners/UserListener.java
- src/main/java/com/example/habitstracker/repository/UserPasswordRepository.java
- src/main/java/com/example/habitstracker/services/UserService.java
- src/main/resources/api.yaml
- src/test/java/com/example/habitstracker/integration/tests/DBTest.java
- src/test/java/com/example/habitstracker/integration/tests/UserDTOValidatorTest.java
- src/test/java/com/example/habitstracker/integration/tests/UserTest.java
- src/test/java/com/example/habitstracker/integration/utils/dsl/UserDSL.java
- src/test/java/com/example/habitstracker/unit/tests/UserServiceTest.java
https://github.com/AlibabaRazboinik/habit_tracker/issues/124
> Релизовать обновление пользователя

- src/main/java/com/example/habitstracker/services/HabitListService.java
- src/main/java/com/example/habitstracker/services/HabitService.java
- src/main/java/com/example/habitstracker/services/UserService.java
https://github.com/AlibabaRazboinik/habit_tracker/issues/128
> Убрать возращаемые типы у методов создания пользователя и привычки

- src/main/java/com/example/habitstracker/models/Habit.java
- src/main/java/com/example/habitstracker/models/HabitList.java
- src/main/java/com/example/habitstracker/models/UserEntity.java
- src/main/java/com/example/habitstracker/models/UserPassword.java
https://github.com/AlibabaRazboinik/habit_tracker/issues/116
> Убрать аннотацию @EqualsAndHashCode у Entity

- README.md
https://github.com/AlibabaRazboinik/habit_tracker/issues/121
> Добавить описание application.properties в readme.md

- src/main/java/com/example/habitstracker/models/UserEntity.java
- src/test/java/com/example/habitstracker/integration/tests/DBTest.java
https://github.com/AlibabaRazboinik/habit_tracker/issues/110
> Сделать имя пользователя уникальным в бд

- src/test/java/com/example/habitstracker/integration/tests/DBTest.java
https://github.com/AlibabaRazboinik/habit_tracker/issues/137
> Некорректный db тест test_cascadeDeleting

- .github/workflows/to_dockerhub.yml
- Dockerfile
- pom.xml
A few improvements: 
- automatic build 
- publication in the register (create your account and secrets, the repository will also need to be replaced)
> Add workflows

- README.md
- pom.xml
https://github.com/AlibabaRazboinik/habit_tracker/issues/147
> Добавить PMD

- src/main/java/com/example/habitstracker/exceptions/auth/EmptyAuthorizationHeaderException.java
- src/main/java/com/example/habitstracker/mappers/HabitListSerializer.java
- src/main/java/com/example/habitstracker/models/HabitList.java
- src/main/java/com/example/habitstracker/models/UserEntity.java
- src/main/java/com/example/habitstracker/models/UserPassword.java
- src/main/java/com/example/habitstracker/models/listeners/UserListener.java
https://github.com/AlibabaRazboinik/habit_tracker/issues/152
Некоторые замечания от PMD пропустил, т.к. они довольно спорны. Думаю, что здесь нужна тонкая настройка PMD.
> Add info about PMD in readme

- src/main/resources/api.yaml
https://github.com/AlibabaRazboinik/habit_tracker/issues/154
> Добавить строки в api.yaml для UserWithoutPasswordDto
